minor changes

diff --git a/scripts/.local/bin/personal/imgdirs2pdf b/scripts/.local/bin/personal/imgdirs2pdf
--- a/scripts/.local/bin/personal/imgdirs2pdf
+++ b/scripts/.local/bin/personal/imgdirs2pdf
@@ -9,7 +9,7 @@ for item in *; do
         pushd "$dir"
         echo "Generating $(ls -l | wc -l) pages: $dir.pdf"
         rm *.url
-        img2pdf * -o "../$dir.pdf" 2> /dev/null || echo "Couldn't generate $dir.pdf"
+        img2pdf * -o "../$dir.pdf" ${@:1} 2> /dev/null || echo "Couldn't generate $dir.pdf"
         $0
         popd
     fi
